### ISSUE TITLE
MIgrating data using docker

### ISSUE THREAD

**Issue by gpoveda** [electrikhq/charge#1]
Hi,

I have deployed docker installation and everything is ok, however, it seems to be data migration process (php artisan make:migration) it was not included into the docker config file: (https://github.com/electrikhq/charge/blob/master/docker/app/Dockerfile). Checking the db structure by using phpmyadmin I can see there are not tables yet ....

Can you please  explain me how can I manage it ?, also how can create or have acces to the admin user?

I really appreciate all your attention and help

**Comment by neerajsohal** [comment]
Hi,

Sorry you are facing this issue. The package is currently under development and is not fit for production use.

However, You can login into the instance and run the migrations yourself for the time being.

Best,
Neeraj
